excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://HollowRose.github.io
title: HollowRose
tagline: A Blog for Life; Art, Cooking, Crafting and Everything In Between
description: Welcome to the 3-ring circus I call life; Laugh with me at my stupidity, cry with me at my failures (or laugh at me again it's all the same really) as I navigate this crazy ride. I'll share recipes, artwork, crochet and knitting advice, crafting adventures, I'll be sure to answer some requests and share some of pieces of real life with you! 
paginate: 5